version: '3.3'

services:
  db:
    container_name: zozz_db
    image: schtoukai/zozz_db_img
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    restart: always
  reverseproxy:
    container_name: reguthproxy
    image: schtoukai/reguthproxy_img
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    depends_on: 
      - db
  userservice:
    container_name: vlad_thounine
    build:
        context: ./user_manager
        dockerfile: Dockerfile
    image: schtoukai/vlad_thounine_img
    ports:
      - 8081:8081
    depends_on:
      - db
      - reverseproxy
  cardservice:
    container_name: mathiamas
    build:
        context: ./card_manager
        dockerfile: Dockerfile
    image: schtoukai/mathiamas_img
    ports:
      - 8082:8082
    depends_on:
      - db
      - reverseproxy
  storeservice:
    container_name: enzisrael
    build:
        context: ./store_manager
        dockerfile: Dockerfile
    image: schtoukai/enzisrael_img
    ports:
      - 8083:8083
    depends_on:
      - db
      - reverseproxy
  #roomservice:
    #container_name: room_manager
    #build:
        #context: ./Atelier3/room_manager
        #dockerfile: Dockerfile
    #image: schtoukai/cardgame_roomservice
    #ports:
      #- 8084:8084
    #depends_on:
      #- db
      #- reverseproxy
  reactfront:
    container_name: gutenhower
    build:
        context: ./vue
        dockerfile: Dockerfile
    image: schtoukai/gutenhower_img
    ports:
      - 3001:3001
    depends_on:
      - db
      - reverseproxy