version: '3.3'

services:
  db:
    container_name: zozz_db
    image: schtoukai/zozz_db_img
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    restart: always
  reverseproxy:
    container_name: reguthproxy
    image: schtoukai/reguthproxy_img
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    depends_on: 
      - db
  activemq:
    container_name: active_moelle
    image: schtoukai/active_moelle_img
    build:
      context: ./activeMQ
      dockerfile: Dockerfile
    ports:
      - 61616:61616
      - 8161:8161
    depends_on: 
      - db
      - reverseproxy
  userservice:
    container_name: vlad_thounine
    build:
        context: ./springboot/user_manager
        dockerfile: Dockerfile
    image: schtoukai/vlad_thounine_img
    ports:
      - 8081:8081
    environment:
      - spring.activemq.broker-url=tcp://active_moelle:61616
    depends_on:
      - db
      - reverseproxy
      - activemq
  cardservice:
    container_name: mathiamas
    build:
        context: ./springboot/card_manager
        dockerfile: Dockerfile
    image: schtoukai/mathiamas_img
    ports:
       - 8082:8082
    depends_on:
      - db
      - reverseproxy
      - activemq
  storeservice:
    container_name: enzisrael
    build:
        context: ./springboot/store_manager
        dockerfile: Dockerfile
    image: schtoukai/enzisrael_img
    ports:
      - 8083:8083
    depends_on:
      - db
      - reverseproxy
      - activemq
  authservice:
    container_name: moauthias
    build:
        context: ./springboot/auth_manager
        dockerfile: Dockerfile
    image: schtoukai/moauthias_img
    ports:
      - 8084:8084
    depends_on:
      - db
      - reverseproxy
      - activemq
  notifservice:
    container_name: thonyfier
    build:
        context: ./springboot/notif_manager
        dockerfile: Dockerfile
    image: schtoukai/thonyfier_img
    ports:
      - 8085:8085
    depends_on:
      - db
      - reverseproxy
      - activemq
  vuefront:
    container_name: gutenhower
    build:
        context: ./react
        dockerfile: Dockerfile
    image: schtoukai/gutenhower_img
    ports:
      - 3000:3000
    depends_on:
      - db
      - reverseproxy
      - activemq