DROP TABLE IF EXISTS usermodel;
CREATE TABLE usermodel (
    id BIGSERIAL NOT NULL,
    login VARCHAR(50) DEFAULT NULL,
    pwd VARCHAR(50) DEFAULT NULL,
    account FLOAT,
    lastName VARCHAR(100) DEFAULT NULL,
    surName VARCHAR(100) DEFAULT NULL,
    email VARCHAR(100) DEFAULT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (id)
);

CREATE TABLE cardmodel (
	id  BIGSERIAL NOT NULL,
	name VARCHAR(50) DEFAULT NULL,
	description VARCHAR(3000) DEFAULT NULL,
	family VARCHAR(100) DEFAULT NULL,
	affinity VARCHAR(100) DEFAULT NULL,
	imgUrl VARCHAR(200) DEFAULT NULL,
	smallImgUrl VARCHAR(200) DEFAULT NULL,
	energy FLOAT,
	hp FLOAT,
	defence FLOAT,
	attack FLOAT,
	price FLOAT,
    CONSTRAINT PK_CARD PRIMARY KEY (id)
);
